name: Build and deploy ASP.Net Core app to Azure Web App - AplikacjaDoLosowania

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'  # Użyj wersji .NET 6.0 (lub tej, którą używasz)

      - name: Restore dependencies
        run: dotnet restore AplikacjaDoLosowania/AplikacjaDoLosowania.csproj

      - name: Build with dotnet
        run: dotnet build AplikacjaDoLosowania/AplikacjaDoLosowania.csproj --configuration Release

      - name: Run Tests
        run: dotnet test AplikacjaDoLosowania.Tests/AplikacjaDoLosowania.Tests.csproj

      - name: dotnet publish
        run: dotnet publish AplikacjaDoLosowania/AplikacjaDoLosowania.csproj -c Release -o './myapp'  # Zmieniona ścieżka

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: './myapp'  # Ścieżka do artefaktu, który jest publikowany

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ AZUREAPPSERVICE_CLIENTID_EDF0B7F94621448CB0D9B548ABE4FFDE }}  # Upewnij się, że zmienne w secret są poprawnie ustawione
          tenant-id: ${{ AZUREAPPSERVICE_TENANTID_2C748BB0145047629A5E467567DEC1E8 }}
          subscription-id: ${{ AZUREAPPSERVICE_SUBSCRIPTIONID_3C4EBFDB656846C2A37EEBDD13FDD0D5 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AplikacjaDoLosowania'  # Upewnij się, że nazwa aplikacji jest poprawna
          slot-name: 'Production'
          package: './myapp'  # Ścieżka do artefaktu, który ma zostać wdrożony
